### ISSUE TITLE
java_bytom的sdk源码少程序包了，编译缺少jar程序包

### ISSUE THREAD

**Issue by Wolkin** [chainworld/java-bytom#1]
运行环境：Win 7 64位
                eclipse
                jdk 1.8
运行步骤：git clone 本源码程序导入到本地新建java project项目
发生编译错误：缺少程序包编译错误
![_20180529171003](https://user-images.githubusercontent.com/34227886/40649336-3c4ff546-6363-11e8-8d73-1125a6e6e40c.png)
![_20180529171010](https://user-images.githubusercontent.com/34227886/40649337-3cadce28-6363-11e8-82b9-3cf015d9cbd7.png)

**Comment by niyuelin1990** [comment]
用maven导入项目

**Comment by Wolkin** [comment]
@niyuelin1990 不通用。
建议：1、调整源码路劲（适应普通java项目）。
          2、封装个json包就满足要求。
无需一定要创建maven工程再导入。

**Comment by niyuelin1990** [comment]
java project always use maven  to create project. and  sdk use maven having no problem. so you can familiarize yourself with maven.
